# Generated by Django 5.1.6 on 2025-04-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('url', models.URLField()),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('light-blue', 'Light blue'), ('green', 'Green'), ('violet', 'Violet'), ('red', 'Red'), ('contrast', 'Contrast')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='community.communityresourcegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'group'), name='unique_community_resource_name_group')],
            },
        ),
    ]
