# Generated by Django 5.2 on 2025-04-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='board.organization'),
        ),
    ]
